In [1]:
from numpy import array
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional
from sklearn.metrics import mean_squared_error
from sklearn import metrics 
import pandas as pd

Using TensorFlow backend.

In [2]:
df = pd.read_excel('owid-covid-data .xlsx')

In [3]:
df

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,new_deaths_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,tests_units
0,ABW,Aruba,2020-03-13,2,2,0,0,18.733,18.733,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,ABW,Aruba,2020-03-20,4,2,0,0,37.465,18.733,0.000,0.000,NaN,NaN,NaN,NaN,NaN
2,ABW,Aruba,2020-03-24,12,8,0,0,112.395,74.930,0.000,0.000,NaN,NaN,NaN,NaN,NaN
3,ABW,Aruba,2020-03-25,17,5,0,0,159.227,46.831,0.000,0.000,NaN,NaN,NaN,NaN,NaN
4,ABW,Aruba,2020-03-26,19,2,0,0,177.959,18.733,0.000,0.000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13075,ZWE,Zimbabwe,2020-04-21,25,0,3,0,1.682,0.000,0.202,0.000,NaN,NaN,NaN,NaN,NaN
13076,ZWE,Zimbabwe,2020-04-22,28,3,3,0,1.884,0.202,0.202,0.000,NaN,NaN,NaN,NaN,NaN
13077,ZWE,Zimbabwe,2020-04-23,28,0,3,0,1.884,0.000,0.202,0.000,NaN,NaN,NaN,NaN,NaN
13078,ZWE,Zimbabwe,2020-04-24,29,1,3,0,1.951,0.067,0.202,0.000,NaN,NaN,NaN,NaN,NaN
13079,ZWE,Zimbabwe,2020-04-25,29,0,4,1,1.951,0.000,0.269,0.067,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df[['location','total_cases']]

In [5]:
df

       location  total_cases
0         Aruba            2
1         Aruba            4
2         Aruba           12
3         Aruba           17
4         Aruba           19
...         ...          ...
13075  Zimbabwe           25
13076  Zimbabwe           28
13077  Zimbabwe           28
13078  Zimbabwe           29
13079  Zimbabwe           29

[13080 rows x 2 columns]

In [6]:
lis1 = dict()
for rows in df.itertuples():
    if rows.location not in lis1:
        lis1[rows.location] = []
    lis1[rows.location].append(rows.total_cases)

In [7]:
X = []
y = []
for key in lis1.keys():
    lis = lis1[key]
    n = len(lis)
    for i in range(0,n-3):
        temp = lis[i:i+3]
        X.append(temp)
        y.append(lis[i+3])

In [8]:
X = array(X)
X = X.reshape(len(X),1,3)
print(len(y))
X

12462

array([[[ 2,  4, 12]],

       [[ 4, 12, 17]],

       [[12, 17, 19]],

       ...,

       [[25, 25, 28]],

       [[25, 28, 28]],

       [[28, 28, 29]]])

In [9]:
# def split_sequence(sequence, n_steps):
#     X, y = list(), list()
#     for i in range(len(sequence)): 
#         end_ix = i + n_steps
#         if end_ix > len(sequence)-1:
#             break
#         seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
#         X.append(seq_x)
#         y.append(seq_y)
#     return array(X), array(y)

In [10]:
# raw_seq = [48,63,71,81,91,102,112,126,146,171,198,256,334,403,497,571,657,730,883,1019,1139,1326,1635,2059,2545,3105,3684,4289,4778,5351,5916,6729,7600,8454,9212]
# # choose a number of time steps
# n_steps = 3
# # split into samples
# X, y = split_sequence(raw_seq, n_steps)
# print('X=')
# print(X)
# print('y')
# print(y)
# n_features = 1
# X = X.reshape((X.shape[0], X.shape[1], n_features))

In [11]:
X

array([[[ 2,  4, 12]],

       [[ 4, 12, 17]],

       [[12, 17, 19]],

       ...,

       [[25, 25, 28]],

       [[25, 28, 28]],

       [[28, 28, 29]]])

In [12]:
model = Sequential()
model.add(Bidirectional(LSTM(100, activation='relu'), input_shape=(1, 3)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [13]:
model.fit(X, y, epochs=300, verbose=2)

Epoch 1/300
 - 1s - loss: 43489455.5212
Epoch 2/300
 - 1s - loss: 3150969.6530
Epoch 3/300
 - 1s - loss: 1214792.7770
Epoch 4/300
 - 1s - loss: 3933128.6837
Epoch 5/300
 - 1s - loss: 3855479.6828
Epoch 6/300
 - 1s - loss: 2694240.9123
Epoch 7/300
 - 1s - loss: 1877395.7428
Epoch 8/300
 - 1s - loss: 3615012.4574
Epoch 9/300
 - 1s - loss: 3095691.7730
Epoch 10/300
 - 1s - loss: 5186225.2727
Epoch 11/300
 - 1s - loss: 5504848.9303
Epoch 12/300
 - 1s - loss: 28562060.8651
Epoch 13/300
 - 1s - loss: 1821072.5621
Epoch 14/300
 - 1s - loss: 2190823.9849
Epoch 15/300
 - 1s - loss: 3030725.2105
Epoch 16/300
 - 1s - loss: 2023558.2841
Epoch 17/300
 - 1s - loss: 1523246.5297
Epoch 18/300
 - 1s - loss: 2200637.3475
Epoch 19/300
 - 1s - loss: 2101607.6055
Epoch 20/300
 - 1s - loss: 894893.8619
Epoch 21/300
 - 1s - loss: 776002.3024
Epoch 22/300
 - 1s - loss: 1664515.8790
Epoch 23/300
 - 1s - loss: 2274793.5569
Epoch 24/300
 - 1s - loss: 2040840.5193
Epoch 25/300
 - 1s - loss: 8206493.5323
Epoch 26/300
 - 1s - loss: 1440735.1783
Epoch 27/300
 - 1s - loss: 1081923.9501
Epoch 28/300
 - 1s - loss: 1095034.9788
Epoch 29/300
 - 1s - loss: 1652554.1577
Epoch 30/300
 - 1s - loss: 6149862.8459
Epoch 31/300
 - 1s - loss: 1410335.8118
Epoch 32/300
 - 1s - loss: 621473.2742
Epoch 33/300
 - 1s - loss: 1298298.8247
Epoch 34/300
 - 1s - loss: 557924.6104
Epoch 35/300
 - 1s - loss: 1666279.5404
Epoch 36/300
 - 1s - loss: 1878394.9359
Epoch 37/300
 - 1s - loss: 4072704.0846
Epoch 38/300
 - 1s - loss: 678529.6199
Epoch 39/300
 - 1s - loss: 857120.0088
Epoch 40/300
 - 1s - loss: 912280.7076
Epoch 41/300
 - 1s - loss: 1057451.3541
Epoch 42/300
 - 1s - loss: 5257270.5785
Epoch 43/300
 - 1s - loss: 2202000.0836
Epoch 44/300
 - 1s - loss: 2723002.0994
Epoch 45/300
 - 1s - loss: 2246080.8882
Epoch 46/300
 - 1s - loss: 1343621.1943
Epoch 47/300
 - 1s - loss: 1434693.7511
Epoch 48/300
 - 1s - loss: 1052582.4192
Epoch 49/300
 - 1s - loss: 2385185.2449
Epoch 50/300
 - 1s - loss: 1563641.2042
Epoch 51/300
 - 1s - loss: 5620346.6081
Epoch 52/300
 - 1s - loss: 1212667.2196
Epoch 53/300
 - 1s - loss: 2075679.1393
Epoch 54/300
 - 1s - loss: 7468281.9810
Epoch 55/300
 - 1s - loss: 759464.5694
Epoch 56/300
 - 1s - loss: 1846230.7056
Epoch 57/300
 - 1s - loss: 994429.0913
Epoch 58/300
 - 1s - loss: 1372186.4365
Epoch 59/300
 - 1s - loss: 3292884.5870
Epoch 60/300
 - 1s - loss: 2707906.4505
Epoch 61/300
 - 1s - loss: 1078470.0481
Epoch 62/300
 - 1s - loss: 567310.8042
Epoch 63/300
 - 1s - loss: 993560.4537
Epoch 64/300
 - 1s - loss: 5692776.3898
Epoch 65/300
 - 1s - loss: 696567.6529
Epoch 66/300
 - 1s - loss: 1280533.5763
Epoch 67/300
 - 1s - loss: 1094744.5344
Epoch 68/300
 - 1s - loss: 1620511.9005
Epoch 69/300
 - 1s - loss: 2524611.4953
Epoch 70/300
 - 1s - loss: 802000.3121
Epoch 71/300
 - 1s - loss: 2219138.9516
Epoch 72/300
 - 1s - loss: 955485.1645
Epoch 73/300
 - 1s - loss: 1436519.7999
Epoch 74/300
 - 1s - loss: 2693734.7623
Epoch 75/300
 - 1s - loss: 472694.5807
Epoch 76/300
 - 1s - loss: 402599.6919
Epoch 77/300
 - 1s - loss: 1533898.7080
Epoch 78/300
 - 1s - loss: 864225.2684
Epoch 79/300
 - 1s - loss: 491241.4734
Epoch 80/300
 - 1s - loss: 1092084.9421
Epoch 81/300
 - 1s - loss: 1869020.8845
Epoch 82/300
 - 1s - loss: 1389688.1706
Epoch 83/300
 - 1s - loss: 599720.5972
Epoch 84/300
 - 1s - loss: 4870283.4415
Epoch 85/300
 - 1s - loss: 4857532.7169
Epoch 86/300
 - 1s - loss: 1512481.4204
Epoch 87/300
 - 1s - loss: 893154.0147
Epoch 88/300
 - 1s - loss: 2555654.1621
Epoch 89/300
 - 1s - loss: 2909656.0908
Epoch 90/300
 - 1s - loss: 787409.1015
Epoch 91/300
 - 1s - loss: 343983.0286
Epoch 92/300
 - 1s - loss: 3153906.3871
Epoch 93/300
 - 1s - loss: 803116.8874
Epoch 94/300
 - 1s - loss: 1109516.5145
Epoch 95/300
 - 1s - loss: 1207605.9649
Epoch 96/300
 - 1s - loss: 1069118.5280
Epoch 97/300
 - 1s - loss: 847831.6601
Epoch 98/300
 - 1s - loss: 4907694.1639
Epoch 99/300
 - 1s - loss: 387891.8339
Epoch 100/300
 - 1s - loss: 755804.1268
Epoch 101/300
 - 1s - loss: 7430019.7203
Epoch 102/300
 - 1s - loss: 602189.6734
Epoch 103/300
 - 1s - loss: 3196782.8173
Epoch 104/300
 - 1s - loss: 600023.0441
Epoch 105/300
 - 1s - loss: 766561.7485
Epoch 106/300
 - 1s - loss: 737049.4447
Epoch 107/300
 - 1s - loss: 766034.1845
Epoch 108/300
 - 1s - loss: 849435.8647
Epoch 109/300
 - 1s - loss: 621340.2152
Epoch 110/300
 - 1s - loss: 1317611.2719
Epoch 111/300
 - 1s - loss: 1616397.4268
Epoch 112/300
 - 1s - loss: 1552527.3610
Epoch 113/300
 - 1s - loss: 793290.4972
Epoch 114/300
 - 1s - loss: 1541189.1564
Epoch 115/300
 - 1s - loss: 2158733.6980
Epoch 116/300
 - 1s - loss: 687330.6209
Epoch 117/300
 - 1s - loss: 923990.6518
Epoch 118/300
 - 1s - loss: 865542.2019
Epoch 119/300
 - 1s - loss: 498294.4790
Epoch 120/300
 - 1s - loss: 4471719.4663
Epoch 121/300
 - 1s - loss: 395738.5443
Epoch 122/300
 - 1s - loss: 613003.6635
Epoch 123/300
 - 1s - loss: 2304568.3811
Epoch 124/300
 - 1s - loss: 328916.9526
Epoch 125/300
 - 1s - loss: 339705.3550
Epoch 126/300
 - 1s - loss: 968798.5117
Epoch 127/300
 - 1s - loss: 711785.2947
Epoch 128/300
 - 1s - loss: 1309876.8180
Epoch 129/300
 - 1s - loss: 307635.5897
Epoch 130/300
 - 1s - loss: 1203070.5459
Epoch 131/300
 - 1s - loss: 1178458.8754
Epoch 132/300
 - 1s - loss: 709826.6861
Epoch 133/300
 - 1s - loss: 1453861.1208
Epoch 134/300
 - 1s - loss: 989526.3771
Epoch 135/300
 - 1s - loss: 873578.1263
Epoch 136/300
 - 1s - loss: 1020707.1446
Epoch 137/300
 - 1s - loss: 1031162.1544
Epoch 138/300
 - 1s - loss: 772063.3831
Epoch 139/300
 - 1s - loss: 2052120.4758
Epoch 140/300
 - 1s - loss: 400029.7603
Epoch 141/300
 - 1s - loss: 465539.3344
Epoch 142/300
 - 1s - loss: 1573051.5411
Epoch 143/300
 - 1s - loss: 538730.3279
Epoch 144/300
 - 1s - loss: 1106041.8430
Epoch 145/300
 - 1s - loss: 586473.8923
Epoch 146/300
 - 1s - loss: 891789.5340
Epoch 147/300
 - 1s - loss: 282695.6321
Epoch 148/300
 - 1s - loss: 5184903.9972
Epoch 149/300
 - 1s - loss: 230455.5147
Epoch 150/300
 - 1s - loss: 239703.0344
Epoch 151/300
 - 1s - loss: 268361.5596
Epoch 152/300
 - 1s - loss: 375426.3291
Epoch 153/300
 - 1s - loss: 512757.1849
Epoch 154/300
 - 1s - loss: 953103.3607
Epoch 155/300
 - 1s - loss: 484260.6309
Epoch 156/300
 - 1s - loss: 728599.4262
Epoch 157/300
 - 1s - loss: 401972.3556
Epoch 158/300
 - 1s - loss: 329794.1017
Epoch 159/300
 - 1s - loss: 1202356.6538
Epoch 160/300
 - 1s - loss: 485901.4316
Epoch 161/300
 - 1s - loss: 2837208.1764
Epoch 162/300
 - 1s - loss: 236881.9897
Epoch 163/300
 - 1s - loss: 2621471.4914
Epoch 164/300
 - 1s - loss: 508284.8269
Epoch 165/300
 - 1s - loss: 563786.3671
Epoch 166/300
 - 1s - loss: 609108.6407
Epoch 167/300
 - 1s - loss: 1936478.8450
Epoch 168/300
 - 1s - loss: 2383338.6123
Epoch 169/300
 - 1s - loss: 981053.1114
Epoch 170/300
 - 1s - loss: 246260.6341
Epoch 171/300
 - 1s - loss: 335254.8205
Epoch 172/300
 - 1s - loss: 2230322.7220
Epoch 173/300
 - 1s - loss: 323994.0468
Epoch 174/300
 - 1s - loss: 945563.7086
Epoch 175/300
 - 1s - loss: 688837.5318
Epoch 176/300
 - 1s - loss: 236674.0762
Epoch 177/300
 - 1s - loss: 355010.6225
Epoch 178/300
 - 1s - loss: 1004275.4706
Epoch 179/300
 - 1s - loss: 5338564.6617
Epoch 180/300
 - 1s - loss: 489197.3696
Epoch 181/300
 - 1s - loss: 1578030.1243
Epoch 182/300
 - 1s - loss: 496871.0591
Epoch 183/300
 - 1s - loss: 410149.9315
Epoch 184/300
 - 1s - loss: 363445.0867
Epoch 185/300
 - 1s - loss: 553021.0391
Epoch 186/300
 - 1s - loss: 3664904.2132
Epoch 187/300
 - 1s - loss: 845782.9488
Epoch 188/300
 - 1s - loss: 375036.3351
Epoch 189/300
 - 1s - loss: 1092842.0818
Epoch 190/300
 - 1s - loss: 943923.7988
Epoch 191/300
 - 1s - loss: 1573507.1625
Epoch 192/300
 - 1s - loss: 1970259.0157
Epoch 193/300
 - 1s - loss: 569924.5815
Epoch 194/300
 - 1s - loss: 752212.1729
Epoch 195/300
 - 1s - loss: 1438515.9370
Epoch 196/300
 - 1s - loss: 311688.5567
Epoch 197/300
 - 1s - loss: 3158275.7406
Epoch 198/300
 - 1s - loss: 230419.2876
Epoch 199/300
 - 1s - loss: 354619.7355
Epoch 200/300
 - 1s - loss: 2649308.7350
Epoch 201/300
 - 1s - loss: 575761.1929
Epoch 202/300
 - 1s - loss: 629199.8649
Epoch 203/300
 - 1s - loss: 425044.5515
Epoch 204/300
 - 1s - loss: 2622544.5696
Epoch 205/300
 - 1s - loss: 294186.5155

Epoch 206/300
 - 1s - loss: 863832.0462
Epoch 207/300
 - 1s - loss: 416919.7730
Epoch 208/300
 - 1s - loss: 1690651.1760
Epoch 209/300
 - 1s - loss: 1910931.4546
Epoch 210/300
 - 1s - loss: 383458.4241
Epoch 211/300
 - 1s - loss: 582574.5678
Epoch 212/300
 - 1s - loss: 958425.6332
Epoch 213/300
 - 1s - loss: 637980.2169
Epoch 214/300
 - 1s - loss: 804151.8894
Epoch 215/300
 - 1s - loss: 244755.8956
Epoch 216/300
 - 1s - loss: 398820.3480
Epoch 217/300
 - 1s - loss: 461601.4182
Epoch 218/300
 - 1s - loss: 450270.3329
Epoch 219/300
 - 1s - loss: 344915.7245
Epoch 220/300
 - 1s - loss: 1657705.9253
Epoch 221/300
 - 1s - loss: 409269.8563
Epoch 222/300
 - 1s - loss: 914836.4987
Epoch 223/300
 - 1s - loss: 358794.3572
Epoch 224/300
 - 1s - loss: 2852563.5752
Epoch 225/300
 - 1s - loss: 679358.2687
Epoch 226/300
 - 1s - loss: 533609.6649
Epoch 227/300
 - 1s - loss: 634692.8615
Epoch 228/300
 - 1s - loss: 479433.9629
Epoch 229/300
 - 1s - loss: 508854.9773
Epoch 230/300
 - 1s - loss: 491619.2718
Epoch 231/300
 - 1s - loss: 1144472.4686
Epoch 232/300
 - 1s - loss: 1190500.4428
Epoch 233/300
 - 1s - loss: 294115.2451
Epoch 234/300
 - 1s - loss: 308815.1225
Epoch 235/300
 - 1s - loss: 328760.1770
Epoch 236/300
 - 1s - loss: 2276621.8961
Epoch 237/300
 - 1s - loss: 594554.3136
Epoch 238/300
 - 1s - loss: 194499.3444
Epoch 239/300
 - 1s - loss: 318507.8343
Epoch 240/300
 - 1s - loss: 448959.2794
Epoch 241/300
 - 1s - loss: 328645.9038
Epoch 242/300
 - 1s - loss: 823631.8971
Epoch 243/300
 - 1s - loss: 316244.6937
Epoch 244/300
 - 1s - loss: 328562.2432
Epoch 245/300
 - 1s - loss: 945776.8692
Epoch 246/300
 - 1s - loss: 243313.7874
Epoch 247/300
 - 1s - loss: 647789.5062
Epoch 248/300
 - 1s - loss: 1775681.7825
Epoch 249/300
 - 1s - loss: 1162707.9117
Epoch 250/300
 - 1s - loss: 246773.8789
Epoch 251/300
 - 1s - loss: 866283.3458
Epoch 252/300
 - 1s - loss: 445558.3787
Epoch 253/300
 - 1s - loss: 6088190.8346
Epoch 254/300
 - 1s - loss: 537799.3139
Epoch 255/300
 - 1s - loss: 300378.9099
Epoch 256/300
 - 1s - loss: 181220.3032
Epoch 257/300
 - 1s - loss: 1383815.0966
Epoch 258/300
 - 1s - loss: 166536.1630
Epoch 259/300
 - 1s - loss: 2702009.2876
Epoch 260/300
 - 1s - loss: 457813.4619
Epoch 261/300
 - 1s - loss: 183213.6667
Epoch 262/300
 - 1s - loss: 267968.4672
Epoch 263/300
 - 1s - loss: 187303.7439
Epoch 264/300
 - 1s - loss: 652286.9693
Epoch 265/300
 - 1s - loss: 680056.3657
Epoch 266/300
 - 1s - loss: 325623.4953
Epoch 267/300
 - 1s - loss: 1796718.8326
Epoch 268/300
 - 1s - loss: 285197.0559
Epoch 269/300
 - 1s - loss: 1261514.1812
Epoch 270/300
 - 1s - loss: 528407.1786
Epoch 271/300
 - 1s - loss: 271624.4444
Epoch 272/300
 - 1s - loss: 1168262.3073
Epoch 273/300
 - 1s - loss: 369533.2560
Epoch 274/300
 - 1s - loss: 783780.7026
Epoch 275/300
 - 1s - loss: 353575.6007
Epoch 276/300
 - 1s - loss: 421139.4290
Epoch 277/300
 - 1s - loss: 416420.3183
Epoch 278/300
 - 1s - loss: 719277.0489
Epoch 279/300
 - 1s - loss: 252655.1469
Epoch 280/300
 - 1s - loss: 1047405.5178
Epoch 281/300
 - 1s - loss: 237805.7314
Epoch 282/300
 - 1s - loss: 333445.8925
Epoch 283/300
 - 1s - loss: 292764.5769
Epoch 284/300
 - 1s - loss: 216043.2691
Epoch 285/300
 - 1s - loss: 522764.9003
Epoch 286/300
 - 1s - loss: 2768526.0673
Epoch 287/300
 - 1s - loss: 167383.1073
Epoch 288/300
 - 1s - loss: 826605.9865
Epoch 289/300
 - 1s - loss: 2188916.4995
Epoch 290/300
 - 1s - loss: 231426.8967
Epoch 291/300
 - 1s - loss: 243304.5043
Epoch 292/300
 - 1s - loss: 312311.0743
Epoch 293/300
 - 1s - loss: 221483.0216
Epoch 294/300
 - 1s - loss: 1068643.2932
Epoch 295/300
 - 1s - loss: 209620.2003
Epoch 296/300
 - 1s - loss: 595542.9719
Epoch 297/300
 - 1s - loss: 1911361.0038
Epoch 298/300
 - 1s - loss: 257568.4700
Epoch 299/300
 - 1s - loss: 396072.6334
Epoch 300/300
 - 1s - loss: 463417.7442

In [17]:
# a=7600
# b=8454
# c=9212
# for _ in range(10):
#     x_input = array([a, b, c])
  
#     x_input = x_input.reshape((1, n_steps, n_features))
#     yhat = model.predict(x_input, verbose=0)
#     print(yhat)
#     a=b
#     b=c
#     c=yhat
# D=[]
# n=35
# scale=[]
# for i in range(0,9500,500):
#     scale.append(i)
# for i in range(4,(n+1),1):
#     D.append(i)

#plt.figure(figsize=(18,10))
#plt.xlabel("Cases")
#plt.ylabel("day")
#plt.plot(D,y)
#plt.plot(D,yhatd)
#plt.yticks(scale)
import random
X_test = []
y_test = []
indexes = random.sample(range(0,len(y)-1),100)
for i in indexes:
    X_test.append(X[i])
    y_test.append(y[i])
X_test = array(X_test)
X_test.shape

(100, 1, 3)

In [18]:
yhatd=model.predict(X_test)
print(model.summary())
print("k")

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
bidirectional_1 (Bidirection (None, 200)               83200
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201
=================================================================
Total params: 83,401
Trainable params: 83,401
Non-trainable params: 0
_________________________________________________________________
None
k

In [19]:
# print(yhatd)
# print(y_test)
# print('MSE=')
from sklearn import metrics
# print(metrics.mean_squared_error(yhatd,y_test))
print ("MSE   ",metrics.mean_squared_error(yhatd,y_test))
print ("RMSE   ",metrics.mean_squared_error(yhatd,y_test)**0.5)

MAE = 0
for i in range(0,len(y_test)):
    MAE = MAE + (abs(y_test[i]-yhatd[i]))
print('MAE   ',MAE/len(y_test))
# Q=X[0:len(X)]
# P=yhatd[0:len(yhatd)]
# r=[]
# for i in range(len(X)):
# 	r.append(i)
# sum=0
# for i in range(len(r)):
#   #print(abs(Q[i]-P[i]))
#   sum=sum+abs(((yhatd[i]-y[i])/y[i]))
#   #print(sum)

#   #print(abs([i]-yhatd[i]))
# #print('a')
# print(sum,len(r))
# print("MAPI", (sum/len(r))*100)

MSE    123508.15461979488
RMSE    351.4372698217918
MAE    [85.11386252]